<a href="https://colab.research.google.com/github/kunalpohakar/TensorFlow_Developer_Certificate_Bootcamp/blob/main/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this notebook, we're going to cover some of the most fundamentals concepts of tensors using Tensorflow

More specifically, we're going to cover:
* Introduction of Tensors
* Getting information from tensors
* manipulating Tensors
* Tenors & Numpy
* Using @tf.function ( a way to speed up your regular python function )
* Using GPUs with Tensorflow (or TPUs)
* Exercises to try for yourself!

In [3]:
## Introduction to Tensors

In [4]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [5]:
# Create tensors with tf.constant
# Scalar is a tensor with only one element, which means it has no dimensions
scalar = tf.constant(7, 2)
scalar

<tf.Tensor: shape=(), dtype=float64, numpy=7.0>

In [6]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimensions of our vector
vector.ndim

1

In [9]:
# create a matrix ( has more than 1 dimensions )
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [8., 9.]], dtype = tf.float16) # Specify the data type with dtype parameter
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],[4, 5, 6]],
                      [[7, 8, 9],[10, 11, 12]],
                      [[13, 14, 15],[16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

What we've created so far

* Scalar : a single dimensions
* Vector : a number with direction (e.g a wind with speed)
* matrix : a 2- dimensional array of numbers
* Tensor : an n - dimensional array of numbers ( when n can be any number, a 0-dimensional tensor is a scalar, 1-dimensional tensor is a vector )


## Creating Tensors with `tf.variable`

In [15]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [16]:
# Create the same tensor with `tf.Variable()` as above

changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
# Let's try chnage noe of the element of our changable tensor
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors

Random tensors are tensors of some abirtary size which content random numbers.


In [18]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [19]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in tensor

In [20]:
# Shuffle the tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

⚒ **Exercise:** Read through documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.*italicized text*

It looks like if we want our shuffled tensors to be in the same order , we've got the use the global level random seed as well as operational level random seed:

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [22]:
practice_shuffle = tf.constant([[[1, 2], [3, 4], [5, 6]],
                                [[7, 8], [9, 10], [11, 12]],
                                [[13, 14], [15, 16], [17, 18]],
                                [[19, 20], [21, 22], [23, 24]],
                                [[25, 26], [27, 28], [29, 30]]])
practice_shuffle

<tf.Tensor: shape=(5, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]]], dtype=int32)>

In [23]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(practice_shuffle, seed=42) # operational level random seed

<tf.Tensor: shape=(5, 3, 2), dtype=int32, numpy=
array([[[19, 20],
        [21, 22],
        [23, 24]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[25, 26],
        [27, 28],
        [29, 30]]], dtype=int32)>

### Other ways to make tensors

In [24]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
# Create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn Numpy arrays into Tensors

The main difference between Numpy arrays and tensorflow Tensor is that tensors can be run on GPU ( must Faster for numerical Computing )

In [26]:
# You can also turn numpy array into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Create a Numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [28]:
B.ndim

1

In [29]:
A.ndim

3

In [30]:
C = tf.constant(numpy_A, shape=(3, 8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

## Getting Information from Tensors

When dealing with tensors you probably want to be aware of the following attributes:

* Shape
* Rank
* Axis or dimensions
* Size

In [31]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [33]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
2 * 3 * 4 * 5

120

In [35]:
# Get various attributes of our tensor
print("Datatype of every element : ", rank_4_tensor.dtype)
print("Number of Dimensions (rank) : ", rank_4_tensor.ndim)
print("Sahpe of tensor : ", rank_4_tensor.shape)
print("Elements along the 0 axis : ", rank_4_tensor.shape[0])
print("Elements along the last axis : ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor : ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor : ", tf.size(rank_4_tensor).numpy())

Datatype of every element :  <dtype: 'float32'>
Number of Dimensions (rank) :  4
Sahpe of tensor :  (2, 3, 4, 5)
Elements along the 0 axis :  2
Elements along the last axis :  5
Total number of elements in our tensor :  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor :  120


### Indexing tensors

Tensors can be indexed just like python list.

In [36]:
# Get the firest 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
# Get the first element from each dimensions from each index except for the final one
rank_4_tensor[:1, :1, :, :1 ]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [38]:
# Create rank 2 tensor ( 2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [2,3]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [39]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]], dtype=int32)>

In [40]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[ : , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [41]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [42]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2_tensor, axis=0) # "0" means expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  3]]], dtype=int32)>

In [44]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]], dtype=int32)>

## Manipulating Tensors ( tensor operation )

**Baisc Operation**
`+`, `-`, `*`, `/`

In [45]:
# You can add values to a tensor using addition operator

tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [46]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [47]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [48]:
# Subtraction
tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

In [49]:
# We can use tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## **Matrix Multiplication**

In machine learning, matrix multiplication is one of common tensor operations

There are two rules our tensor ( or metrices ) need to fulfill if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions

In [50]:
# Matrix Multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [51]:
# Matrix Multiplication using python operator @

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [52]:
# Create a tensor (3, 2)
tensor_1 = tf.constant([[1, 2, 5],
                        [7, 2, 1],
                        [3, 3, 3]])
tensor_2 = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])

tensor_1, tensor_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [53]:
tensor_multi = tf.matmul(tensor_1, tensor_2)
tensor_multi

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [54]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
y = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])

x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [55]:
x @ tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [37, 19, 50],
       [57, 31, 78]], dtype=int32)>

In [56]:
x.shape, y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [57]:
tf.reshape(x, [2, 3]) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 18,  43],
       [ 48, 103]], dtype=int32)>

In [58]:
# we can do this with the Transpose

x, tf.transpose(x), tf.reshape(x, [2, 3])

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [59]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 66],
       [36, 86]], dtype=int32)>

In [60]:
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 66],
       [36, 86]], dtype=int32)>

Generally, When performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose ( rather than reshape ) one of the tensors to get satisfy the matrix multiplication rules.

# **Aggregation**

In [61]:
k = tf.constant([-7, -10])
k

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [62]:
tf.abs(k)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor

In [63]:
# Create a random tensor with values between 0 to 100 of size 50
e = tf.constant(np.random.randint(0, 100, size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([30, 50, 10, 78, 42, 55,  1, 14, 63, 48, 88,  1, 70,  5, 36, 94, 24,
       74, 62, 14, 86, 78, 60, 96, 68, 22,  9, 80, 90, 92, 87, 51, 71, 45,
       93, 88, 68, 35, 95, 67, 87, 11, 48,  5, 92, 93, 89, 37, 23, 44])>

In [64]:
# Find the minimum
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [65]:
# find the maximum
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [66]:
# Find the mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [67]:
# Get the sum of a tensor
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2769>

In [68]:
# find the variance
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=934>

In [69]:
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.567232>

In [70]:
tf.math.reduce_variance(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=934.35565>

## Squeezing the tensors ( removing all single dimesnions )

In [71]:
tf.random.set_seed(42)
F = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
F

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [72]:
F.shape

TensorShape([1, 1, 1, 1, 50])

In [73]:
F_squeeze = tf.squeeze(F)
F_squeeze, F_squeeze.shape


(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One Hot Encoding tensors

In [74]:
# Create a list of indices
list_1 = [0, 1, 2, 3] # Could be red, gree, blue, yellow

# One hot encode our list of indices
tf.one_hot(list_1, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [75]:
# Specify custom values for one hot encode
tf.one_hot(list_1, depth=4, on_value = "Yes", off_value = "No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

## Squaring, log, Square root



In [76]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [77]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [78]:
# Find the Square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [79]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# **Tensors & NumPy**

Tensorflow interacts beautifully with numpy arrays.

In [80]:
# Create a tensor directly from a numpy array
J = tf.constant(np.array([2., 3., 4.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [81]:
# convert our tensors to numpy array
np.array(J), type(np.array(J))

(array([2., 3., 4.]), numpy.ndarray)

In [82]:
# convert numpy array to tensors
J.numpy(), type(J.numpy())

(array([2., 3., 4.]), numpy.ndarray)

In [83]:
J = tf.constant([3.])
J.numpy()[0]

3.0

## Finding access to GPU

In [84]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [85]:
!nvidia-smi

Tue Mar 19 14:55:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0              25W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## **🛠 00. TensorFlow Fundamentals Exercises**

---

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2. Find the shape, rank and size of the tensors you created in 1.

3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

4. Multiply the two tensors you created in 3 using matrix multiplication.

5. Multiply the two tensors you created in 3 using dot product.

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

7. Find the min and max values of the tensor you created in 6 along the first axis.

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

10. One-hot encode the tensor you created in 9.

In [99]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
scalar = tf.constant(10, 2)

vector = tf.constant([10, 7])

matrix = tf.constant([[10, 7],
                      [3, 2]])

tensor = tf.constant([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])

scalar, scalar.ndim, vector, vector.ndim, matrix, matrix.ndim, tensor, tensor.ndim

(<tf.Tensor: shape=(), dtype=float64, numpy=10.0>,
 0,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 1,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  2]], dtype=int32)>,
 2,
 <tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12]]], dtype=int32)>,
 3)

In [100]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([3, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [124]:
A = tf.random.uniform([5, 300], minval=0, maxval=1)
B = tf.random.uniform([5, 300], minval=0, maxval=1)

A, B

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
         0.2584542 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936

In [125]:
A.shape, B.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [127]:
C = tf.matmul(A, tf.transpose(B))
C

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.71399 , 80.87825 , 78.3285  , 78.25969 , 79.13057 ],
       [70.12708 , 72.09945 , 70.16779 , 73.24609 , 74.27741 ],
       [75.16    , 79.52857 , 76.746445, 78.14266 , 77.286804],
       [77.11355 , 75.401215, 72.793785, 75.06638 , 75.206535],
       [79.87285 , 83.40138 , 78.57372 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [128]:
A * B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.50998044, 0.30451736, 0.01618501, ..., 0.3357493 , 0.0698769 ,
        0.23107657],
       [0.0296768 , 0.05186556, 0.51247376, ..., 0.4033517 , 0.10968234,
        0.14504547],
       [0.00674238, 0.17331377, 0.11139643, ..., 0.15974203, 0.31482717,
        0.9880052 ],
       [0.01282308, 0.06803418, 0.04070826, ..., 0.51570535, 0.01522908,
        0.14413354],
       [0.3336517 , 0.18272708, 0.91464335, ..., 0.2465836 , 0.09393981,
        0.05832076]], dtype=float32)>

In [130]:
D = tf.random.uniform([224, 224, 3], minval=0, maxval=1)
E = tf.random.uniform([224, 224, 3], minval=0, maxval=1)

D, E

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.95831835, 0.01680839, 0.3156035 ],
         [0.16013157, 0.7148702 , 0.7892921 ],
         [0.11484027, 0.33310425, 0.21091413],
         ...,
         [0.6279857 , 0.85051286, 0.9490392 ],
         [0.62438786, 0.2802421 , 0.18754554],
         [0.9087832 , 0.46846092, 0.5317346 ]],
 
        [[0.85744655, 0.51288927, 0.18603599],
         [0.04882693, 0.78045344, 0.79377043],
         [0.9356363 , 0.32798207, 0.15949786],
         ...,
         [0.6933085 , 0.5420611 , 0.1860913 ],
         [0.7326596 , 0.9234495 , 0.07200372],
         [0.5471792 , 0.24985266, 0.14673471]],
 
        [[0.5033684 , 0.7000841 , 0.21468806],
         [0.9304948 , 0.17212296, 0.720364  ],
         [0.6657183 , 0.17304075, 0.7110392 ],
         ...,
         [0.35423398, 0.126225  , 0.24436975],
         [0.096439  , 0.06387579, 0.32836854],
         [0.15067935, 0.6084572 , 0.47766674]],
 
        ...,
 
        [[0.23573959, 0.42224514

In [136]:
min_value = tf.reduce_min(D, axis=0)
max_value = tf.reduce_max(D, axis=0)

min_value, max_value

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[6.28840923e-03, 5.36608696e-03, 3.28612328e-03],
        [1.78635120e-03, 7.69615173e-04, 4.28605080e-03],
        [9.94515419e-03, 1.72972679e-04, 2.14409828e-03],
        [4.43828106e-03, 4.51648235e-03, 4.74357605e-03],
        [9.86492634e-03, 2.01439857e-03, 5.80573082e-03],
        [6.59704208e-03, 6.00981712e-03, 6.77955151e-03],
        [3.43513489e-03, 1.48499012e-03, 1.11581087e-02],
        [7.17639923e-04, 1.25019550e-02, 4.83334064e-03],
        [1.23023987e-03, 2.21967697e-03, 3.09741497e-03],
        [4.44173813e-04, 2.16341019e-03, 1.23655796e-03],
        [2.60603428e-03, 8.85558128e-03, 4.47070599e-03],
        [8.30650330e-04, 4.86719608e-03, 2.52771378e-03],
        [4.39465046e-03, 2.57611275e-04, 1.97972059e-02],
        [1.96933746e-04, 2.87055969e-04, 2.14099884e-04],
        [7.20083714e-03, 1.23764277e-02, 3.44371796e-03],
        [6.76095486e-03, 9.66906548e-04, 9.12785530e-04],
        [6.90650940e-

In [139]:
tf.random.set_seed(42)
F = tf.constant(tf.random.uniform(shape=[224, 224, 3]), shape=(1, 224, 224, 3))
F, F.shape

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.6645621 , 0.44100678, 0.3528825 ],
          [0.46448255, 0.03366041, 0.68467236],
          [0.74011743, 0.8724445 , 0.22632635],
          ...,
          [0.42612267, 0.09686017, 0.16105258],
          [0.1487099 , 0.04513884, 0.9497483 ],
          [0.4393103 , 0.28527975, 0.96971095]],
 
         [[0.73308516, 0.5657046 , 0.33238935],
          [0.8838178 , 0.87544763, 0.56711245],
          [0.8879347 , 0.47661996, 0.42041814],
          ...,
          [0.7716515 , 0.9116473 , 0.3229897 ],
          [0.43050945, 0.83253574, 0.45549798],
          [0.29816985, 0.9639522 , 0.3316357 ]],
 
         [[0.41132426, 0.2179662 , 0.53570235],
          [0.5112119 , 0.6484759 , 0.8894886 ],
          [0.42459428, 0.20189774, 0.85781324],
          ...,
          [0.02888799, 0.3995477 , 0.11355484],
          [0.68524575, 0.04945195, 0.17778492],
          [0.97627187, 0.79811585, 0.9411576 ]],
 
         ...,
 
       

In [141]:
F_squeeze = tf.squeeze(F)
F_squeeze, F_squeeze.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.6645621 , 0.44100678, 0.3528825 ],
         [0.46448255, 0.03366041, 0.68467236],
         [0.74011743, 0.8724445 , 0.22632635],
         ...,
         [0.42612267, 0.09686017, 0.16105258],
         [0.1487099 , 0.04513884, 0.9497483 ],
         [0.4393103 , 0.28527975, 0.96971095]],
 
        [[0.73308516, 0.5657046 , 0.33238935],
         [0.8838178 , 0.87544763, 0.56711245],
         [0.8879347 , 0.47661996, 0.42041814],
         ...,
         [0.7716515 , 0.9116473 , 0.3229897 ],
         [0.43050945, 0.83253574, 0.45549798],
         [0.29816985, 0.9639522 , 0.3316357 ]],
 
        [[0.41132426, 0.2179662 , 0.53570235],
         [0.5112119 , 0.6484759 , 0.8894886 ],
         [0.42459428, 0.20189774, 0.85781324],
         ...,
         [0.02888799, 0.3995477 , 0.11355484],
         [0.68524575, 0.04945195, 0.17778492],
         [0.97627187, 0.79811585, 0.9411576 ]],
 
        ...,
 
        [[0.9019445 , 0.27011132

In [147]:
tensor = tf.random.uniform([10], minval=0, maxval=10)
tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([7.402308 , 3.3938193, 5.692506 , 4.481139 , 2.9285502, 4.260056 ,
       6.2890387, 6.91061  , 3.0925727, 8.92366  ], dtype=float32)>

In [150]:
index = tf.math.argmax(tensor)
print(index)

tf.Tensor(9, shape=(), dtype=int64)


In [154]:
tensor, tensor.shape

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([7.402308 , 3.3938193, 5.692506 , 4.481139 , 2.9285502, 4.260056 ,
        6.2890387, 6.91061  , 3.0925727, 8.92366  ], dtype=float32)>,
 TensorShape([10]))

In [158]:
tf.one_hot(tf.cast(tensor, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>

In [159]:
tf.one_hot(tf.cast(tensor, dtype=tf.int32), depth=10, on_value='yes', off_value='no')

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'yes', b'no',
        b'no'],
       [b'no', b'no', b'no', b'yes', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'yes', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'yes', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'yes', b'no', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'yes', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'yes', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'yes', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'yes', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'yes',
        b'no']], dtype=object)>